"""update models 3

Revision ID: 810ba406f441
Revises: c975de0f6bfa
Create Date: 2025-04-30 22:37:10.023043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810ba406f441'
down_revision = 'c975de0f6bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('products_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['seller_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_product_id_fkey', type_='foreignkey')
        batch_op.drop_column('seller_name')
        batch_op.drop_column('product_name')
        batch_op.drop_column('image_url')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('seller_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('transactions_product_id_fkey', 'products', ['product_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###
