"""delete detail field

Revision ID: d75cc5cbc3b1
Revises: 3925fb20e15b
Create Date: 2025-05-01 00:00:48.337188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75cc5cbc3b1'
down_revision = '3925fb20e15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('detail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
